#! /usr/bin/env bash

set -eu

# this function is called when Ctrl-C is sent
function trap_ctrlc ()
{
    docker compose down &> /dev/null
    exit 2
}

# initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2

# remove database between runs
rm -rf ./db/data
mkdir ./db/data
touch ./db/data/.keep

# launch database
docker compose pull
docker compose up -d postgres

# run specs
exit_code="0"
docker compose run \
        --rm \
        test "$@" \
    || exit_code="$?"

# clean up environment
docker compose down &> /dev/null
exit ${exit_code}
