#! /usr/bin/env bash

set -eu

# this function is called when Ctrl-C is sent
function trap_ctrlc ()
{
    docker compose down &> /dev/null
    exit 2
}

# initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2

# grab the latest version of the database
# clean any existing data and launch it
docker compose pull
docker compose run --rm postgres sh -c "rm -rf /var/lib/postgresql/data/*"
docker compose up -d postgres

# run specs
exit_code="0"
docker compose run \
        --rm \
        test "$@" \
    || exit_code="$?"

# clean up environment
docker compose down &> /dev/null

if [ "$exit_code" -ne 0 ]; then
    echo "Test failed. Database state is available in the container at /var/lib/postgresql/data for inspection."
    echo "You can inspect with password: password"
    echo "  * docker compose up -d postgres"
    echo "  * docker exec -it postgres psql -U postgres -d development"
fi

exit ${exit_code}
