require "uuid/json"
require "random/secure"
require "crypto/subtle"
require "digest/sha256"

class App::Models::ApiKey < ::PgORM::Base
  table :api_keys

  default_primary_key id : UUID, autogenerated: true

  attribute user_id : UUID
  attribute name : String
  attribute key_hash : String
  attribute key_prefix : String
  attribute scopes : Array(String) = [] of String
  attribute expires_at : Time?
  attribute last_used_at : Time?

  belongs_to :user

  include PgORM::Timestamps

  # Generate a new API key and return the raw key (only shown once)
  def self.create_for_user(user : User, name : String, scopes : Array(String) = [] of String, expires_at : Time? = nil) : {ApiKey, String}
    raw_key = generate_key
    key_hash = hash_key(raw_key)
    key_prefix = raw_key[0, 8]

    api_key = new(
      user_id: user.id,
      name: name,
      key_hash: key_hash,
      key_prefix: key_prefix,
      scopes: scopes,
      expires_at: expires_at
    )
    api_key.save!

    {api_key, raw_key}
  end

  # Find API key by raw key
  def self.find_by_key(raw_key : String) : ApiKey?
    return nil if raw_key.size < 8

    key_hash = hash_key(raw_key)
    find_by?(key_hash: key_hash)
  end

  # Verify and return the API key if valid
  def self.authenticate(raw_key : String) : ApiKey?
    api_key = find_by_key(raw_key)
    return nil unless api_key
    return nil if api_key.expired?

    api_key.touch_last_used!
    api_key
  end

  def expired? : Bool
    return false unless exp = expires_at
    Time.utc > exp
  end

  def valid_key? : Bool
    !expired?
  end

  def has_scope?(scope : String) : Bool
    scopes.empty? || scopes.includes?(scope) || scopes.includes?("*")
  end

  def touch_last_used!
    self.last_used_at = Time.utc
    save!
  end

  private def self.generate_key : String
    "sk_" + Random::Secure.hex(24)
  end

  private def self.hash_key(key : String) : String
    Digest::SHA256.hexdigest(key)
  end
end
