require "uuid/json"
require "json"

class App::Models::AuditLog < ::PgORM::Base
  table :audit_logs

  default_primary_key id : UUID, autogenerated: true

  attribute user_id : UUID?
  attribute organization_id : UUID?
  attribute action : String
  attribute resource_type : String
  attribute resource_id : UUID?
  attribute details : JSON::Any?
  attribute ip_address : String?
  attribute user_agent : String?

  attribute created_at : Time = Time.utc

  belongs_to :user
  belongs_to :organization

  # Action constants
  module Actions
    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"
    LOGIN  = "login"
    LOGOUT = "logout"
    INVITE = "invite"
    JOIN   = "join"
    LEAVE  = "leave"
  end

  # Resource type constants
  module Resources
    USER              = "user"
    ORGANIZATION      = "organization"
    GROUP             = "group"
    DOMAIN            = "domain"
    MEMBER            = "member"
    INVITE            = "invite"
    API_KEY           = "api_key"
    OAUTH_APPLICATION = "oauth_application"
    OAUTH_TOKEN       = "oauth_token"
  end

  def self.log(
    action : String,
    resource_type : String,
    resource_id : UUID? = nil,
    user : User? = nil,
    organization : Organization? = nil,
    details : Hash(String, JSON::Any::Type)? = nil,
    ip_address : String? = nil,
    user_agent : String? = nil,
  ) : AuditLog
    log = new(
      action: action,
      resource_type: resource_type,
      resource_id: resource_id,
      user_id: user.try(&.id),
      organization_id: organization.try(&.id),
      details: details ? JSON::Any.new(details.transform_values { |v| JSON::Any.new(v) }) : nil,
      ip_address: ip_address,
      user_agent: user_agent
    )
    log.save!
    log
  end
end
