class App::Models::Domain < ::PgORM::Base
  table :domains

  default_primary_key id : UUID, autogenerated: true
  attribute name : String
  attribute domain : String
  attribute description : String?

  attribute organization_id : UUID
  belongs_to :organization, class_name: Organization

  include PgORM::Timestamps

  before_save do
    self.name = name.strip
    self.domain = domain.strip.downcase
    self.description = description.try(&.strip.presence)
  end

  validates :domain, presence: true
  validates :name, presence: true

  ensure_unique :domain
end
