require "pg-orm"

module App::Models
  class EntitlementSnapshot < PgORM::Base
    table :entitlement_snapshots

    default_primary_key id : UUID, autogenerated: true
    attribute org_id : UUID
    attribute enabled_service_keys : Array(String)
    attribute computed_at : Time
    attribute reason : String?

    belongs_to :organization, class_name: Organization, foreign_key: "org_id"

    include PgORM::Timestamps

    validates :org_id, presence: true

    before_save do
      self.enabled_service_keys = enabled_service_keys.uniq
    end
  end
end
