require "uuid/json"
require "./converters"
require "./permissions"

class App::Models::Group < ::PgORM::Base
  table :groups

  default_primary_key id : UUID, autogenerated: true
  attribute name : String
  attribute description : String?
  attribute permission : App::Permissions, converter: App::PGEnumConverter(App::Permissions)

  attribute organization_id : UUID
  belongs_to :organization

  include PgORM::Timestamps

  before_save do
    self.name = name.strip
    self.description = description.try(&.strip.presence)
  end

  validates :name, presence: true

  def users
    User.join(:inner, GroupUser, :user_id).where("group_users.group_id = ?", self.id)
  end

  def admins
    User.join(:inner, GroupUser, :user_id).where("group_users.group_id = ? AND group_users.is_admin = true", self.id)
  end

  def members
    User.join(:inner, GroupUser, :user_id).where("group_users.group_id = ? AND group_users.is_admin = false", self.id)
  end

  def add_user(user : User, is_admin : Bool = false)
    GroupUser.new(
      group_id: self.id,
      user_id: user.id,
      is_admin: is_admin
    ).save!
  end

  def remove_user(user : User)
    GroupUser.find!({self.id, user.id}).destroy
  end

  def user_is_admin?(user : User) : Bool
    GroupUser.where(group_id: self.id, user_id: user.id, is_admin: true).exists?
  end

  def user_is_member?(user : User) : Bool
    GroupUser.where(group_id: self.id, user_id: user.id).exists?
  end

  def invite(email : String, expires : Time? = nil)
    GroupInvite.new(
      email: email,
      group_id: self.id,
      secret: Random::Secure.hex(32),
      expires: expires
    ).save!
  end

  def admin_group? : Bool
    organization.admin_group_id == self.id
  end
end
