require "uuid/json"

class App::Models::GroupInvite < ::PgORM::Base
  table :group_invites

  default_primary_key id : UUID, autogenerated: true
  attribute email : String
  attribute secret : String
  attribute expires : Time?

  attribute group_id : UUID
  belongs_to :group

  include PgORM::Timestamps

  before_save do
    self.email = email.strip.downcase
  end

  validates :email, format: {
    with:    /\A[^@\s]+@[^@\s]+\z/,
    message: "must be a valid email address",
  }

  def expired? : Bool
    return false unless expires
    Time.utc > expires.not_nil!
  end

  def invite_valid? : Bool
    !expired?
  end

  def accept!(user : User? = nil)
    raise Error::Forbidden.new("Invite has expired") if expired?

    # Find or create user if email provided
    target_user = user || User.find_by(email: self.email)

    if target_user.nil?
      raise "User with email #{self.email} not found. User must be created first."
    end

    # Add user to organization if not already a member
    org = group.organization
    unless org.users.where(id: target_user.id).exists?
      org.add(target_user, App::Permissions::User)
    end

    # Add user to group
    group.add_user(target_user)

    # Delete the invite
    destroy

    target_user
  end
end
