require "uuid"
require "uuid/json"
require "pg-orm"
require "./converters"

module App::Models
  class Invoice < PgORM::Base
    table :invoices

    enum Status
      Open
      Paid
      Void
      Uncollectible
    end

    default_primary_key id : UUID, autogenerated: true
    attribute org_id : UUID
    attribute subscription_id : UUID

    attribute period_start : Time
    attribute period_end : Time
    attribute issue_date : Time
    attribute due_date : Time

    attribute amount_total : Int64 # in cents
    attribute status : Status, converter: App::PGEnumConverter(App::Models::Invoice::Status)

    belongs_to :organization, class_name: Organization, foreign_key: "org_id"
    belongs_to :subscription, class_name: Subscription, foreign_key: "subscription_id"
    has_many :payments, class_name: Payment

    include PgORM::Timestamps

    validates :org_id, presence: true
    validates :subscription_id, presence: true
    validates :amount_total, presence: true

    def open?
      status == Status::Open
    end

    def paid?
      status == Status::Paid
    end

    def overdue?
      open? && (due_date < Time.utc)
    end
  end
end
