require "./converters"
require "./permissions"

class App::Models::OrganizationUser < ::PgORM::Base
  table :organization_users

  default_primary_key user_id : UUID, autogenerated: true
  belongs_to :user
  belongs_to :organization

  attribute permission : App::Permissions, converter: App::PGEnumConverter(App::Permissions)

  include PgORM::Timestamps
end
