class App::Models::Organization < ::PgORM::Base
  table :organizations

  default_primary_key id : UUID, autogenerated: true
  attribute name : String
  attribute description : String?

  attribute owner_id : UUID?
  belongs_to :owner, class_name: User

  include PgORM::Timestamps
end
