require "uuid"
require "uuid/json"
require "pg-orm"

module App::Models
  class Payment < PgORM::Base
    table :payments

    default_primary_key id : UUID, autogenerated: true
    attribute invoice_id : UUID
    attribute amount : Int64 # in cents
    attribute paid_at : Time
    attribute provider_key : String
    attribute provider_reference : String?

    belongs_to :invoice, class_name: Invoice

    include PgORM::Timestamps

    validates :invoice_id, presence: true
    validates :amount, presence: true
    validates :paid_at, presence: true
    validates :provider_key, presence: true
  end
end
