require "uuid"
require "uuid/json"
require "pg-orm"

module App::Models
  class Plan < PgORM::Base
    table :plans

    default_primary_key id : UUID, autogenerated: true
    attribute name : String
    attribute billing_interval : String # 'monthly', 'yearly'
    attribute price : Int64             # in cents
    attribute currency : String = "USD"
    attribute service_ids : Array(UUID) = [] of UUID

    include PgORM::Timestamps

    validates :name, presence: true
    validates :billing_interval, inclusion: {in: %w(monthly yearly)}
    validates :price, presence: true
    validates :currency, length: {is: 3}

    before_save do
      self.name = name.strip
      self.currency = currency.upcase
      self.service_ids = service_ids.uniq
    end

    def services
      return [] of Service if service_ids.empty?
      ids = service_ids
      Service.all.to_a.select { |s| ids.includes?(s.id) }
    end
  end
end
