require "uuid"
require "uuid/json"
require "pg-orm"

module App::Models
  class Service < PgORM::Base
    table :services

    default_primary_key id : UUID, autogenerated: true
    attribute name : String
    attribute description : String?
    attribute entitlement_keys : Array(String)

    include PgORM::Timestamps

    validates :name, presence: true

    before_save do
      self.name = name.strip
      self.description = description.try(&.strip.presence)
      self.entitlement_keys = entitlement_keys.uniq
    end
  end
end
