require "uuid"
require "uuid/json"
require "pg-orm"
require "./converters"

module App::Models
  class Subscription < PgORM::Base
    table :subscriptions

    enum State
      Active
      Suspended
      Cancelled
    end
    default_primary_key id : UUID, autogenerated: true
    attribute org_id : UUID
    attribute plan_id : UUID
    attribute state : State, converter: App::PGEnumConverter(App::Models::Subscription::State)

    attribute start_date : Time
    attribute current_period_start : Time
    attribute current_period_end : Time
    attribute next_invoice_at : Time

    attribute payment_terms_days : Int32 = 14
    attribute cutoff_grace_days : Int32 = 7

    belongs_to :organization, class_name: Organization, foreign_key: "org_id"
    belongs_to :plan, class_name: Plan
    has_many :invoices, class_name: Invoice

    include PgORM::Timestamps

    validates :org_id, presence: true
    validates :plan_id, presence: true

    def active?
      state == State::Active
    end

    def suspended?
      state == State::Suspended
    end

    def cancelled?
      state == State::Cancelled
    end
  end
end
