require "crypto/bcrypt/password"

class App::Models::User < ::PgORM::Base
  table :users

  default_primary_key id : UUID, autogenerated: true
  attribute name : String
  attribute email : String
  attribute password_hash : String?

  include PgORM::Timestamps

  has_many :auth_sources, class_name: Auth

  before_save do
    self.email = email.strip.downcase
    self.name = name.strip
  end

  def organizations
    Organization.join(:inner, OrganizationUser, :organization_id).where("organization_users.user_id = ?", self.id)
  end

  # Set password (hashes it automatically)
  def password=(new_password : String)
    @password_hash = Crypto::Bcrypt::Password.create(new_password).to_s
  end

  # Verify password
  def verify_password(password : String) : Bool
    return false unless hash = password_hash
    Crypto::Bcrypt::Password.new(hash).verify(password)
  end
end
