class App::Models::User < ::PgORM::Base
  table :users

  default_primary_key id : UUID, autogenerated: true
  attribute name : String
  attribute email : String

  include PgORM::Timestamps

  has_many :auth_sources, class_name: Auth

  before_save do
    self.email = email.strip.downcase
    self.name = name.strip
  end

  def organizations
    Organization.join(:inner, OrganizationUser, :organization_id).where("organization_users.user_id = ?", self.id)
  end
end
