class App::Models::User < ::PgORM::Base
  table :users

  default_primary_key id : UUID, autogenerated: true
  attribute name : String
  attribute email : String

  attribute created_at : Time, mass_assignment: false
  attribute updated_at : Time, mass_assignment: false

  before_save do
    self.email = email.strip.downcase
    self.name = name.strip
  end
end
